// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: pbtest.proto

package pbtest

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Id        string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Val1      int64  `protobuf:"varint,3,opt,name=val1,proto3" json:"val1,omitempty"`
	Val2      string `protobuf:"bytes,4,opt,name=val2,proto3" json:"val2,omitempty"`
}

func (x *TestItem) Reset() {
	*x = TestItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbtest_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestItem) ProtoMessage() {}

func (x *TestItem) ProtoReflect() protoreflect.Message {
	mi := &file_pbtest_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestItem.ProtoReflect.Descriptor instead.
func (*TestItem) Descriptor() ([]byte, []int) {
	return file_pbtest_proto_rawDescGZIP(), []int{0}
}

func (x *TestItem) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *TestItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TestItem) GetVal1() int64 {
	if x != nil {
		return x.Val1
	}
	return 0
}

func (x *TestItem) GetVal2() string {
	if x != nil {
		return x.Val2
	}
	return ""
}

var File_pbtest_proto protoreflect.FileDescriptor

var file_pbtest_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x62, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x70, 0x62, 0x74, 0x65, 0x73, 0x74, 0x22, 0x60, 0x0a, 0x08, 0x54, 0x65, 0x73, 0x74, 0x49, 0x74,
	0x65, 0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x76, 0x61, 0x6c, 0x31, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x76, 0x61, 0x6c, 0x31, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x61, 0x6c, 0x32, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x76, 0x61, 0x6c, 0x32, 0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x6c, 0x65, 0x78, 0x73, 0x79, 0x73, 0x69, 0x6f,
	0x2f, 0x67, 0x6b, 0x76, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2f, 0x61, 0x75, 0x74, 0x6f, 0x65, 0x6e,
	0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f,
	0x70, 0x62, 0x74, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pbtest_proto_rawDescOnce sync.Once
	file_pbtest_proto_rawDescData = file_pbtest_proto_rawDesc
)

func file_pbtest_proto_rawDescGZIP() []byte {
	file_pbtest_proto_rawDescOnce.Do(func() {
		file_pbtest_proto_rawDescData = protoimpl.X.CompressGZIP(file_pbtest_proto_rawDescData)
	})
	return file_pbtest_proto_rawDescData
}

var file_pbtest_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pbtest_proto_goTypes = []interface{}{
	(*TestItem)(nil), // 0: pbtest.TestItem
}
var file_pbtest_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pbtest_proto_init() }
func file_pbtest_proto_init() {
	if File_pbtest_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pbtest_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pbtest_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbtest_proto_goTypes,
		DependencyIndexes: file_pbtest_proto_depIdxs,
		MessageInfos:      file_pbtest_proto_msgTypes,
	}.Build()
	File_pbtest_proto = out.File
	file_pbtest_proto_rawDesc = nil
	file_pbtest_proto_goTypes = nil
	file_pbtest_proto_depIdxs = nil
}
